name: eks-cluster

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Cluster name'
        required: true
        default: 'expense-dev' # cluster-name
      delete_cluster:
        description: 'Delete cluster after run?'
        required: true
        type: boolean

jobs:
  cluster:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout branch
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install eksctl
      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      # Create EKS Cluster with Spot Nodes and Custom AMI
      - name: Create EKS Cluster Inline     
        run: |
          CLUSTER_NAME="${{ github.event.inputs.cluster_name }}"
          NODEGROUP_NAME="${CLUSTER_NAME}-nodes"
          REGION="${{ secrets.AWS_REGION }}"
          CUSTOM_AMI="ami-0220d79f3f480ecf5"

          eksctl create cluster \
            --name $CLUSTER_NAME \
            --region $REGION \
            --version 1.29 \
            --managed \
            --nodegroup-name $NODEGROUP_NAME \
            --node-type m5.large,c3.large,c4.large,c5.large \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 4 \
            --spot \
            --node-ami $CUSTOM_AMI \
            --node-labels lifecycle=spot \
            --node-taints spot=true:NoSchedule \
            --asg-access \
            --full-ecr-access

      # Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ${{ secrets.AWS_REGION }}

      # Verify nodes
      - name: Verify nodes
        run: |
          kubectl get nodes

      # Delete cluster (optional)
      - name: Delete EKS Cluster
        if: ${{ github.event.inputs.delete_cluster == 'true' }}
        run: |
          echo "Deleting EKS cluster $CLUSTER_NAME..."
          eksctl delete cluster --name $CLUSTER_NAME --region ${{ secrets.AWS_REGION }}